### ISSUE TITLE
The revision is deployed, but traffic cannot flow. steps.javacallout.JavaCalloutInstantiationFailed

### ISSUE THREAD

**Issue by bhatikuldeep** [apigee/iloveapis2015-hmac-httpsignature#2]
Hi @DinoChiesa thanks for these libraries. 
HMAC works fine for me, however httpsig does not work; while deploying apigee egde (on cloud), returns shows this error;

`The revision is deployed, but traffic cannot flow. steps.javacallout.JavaCalloutInstantiationFailed`

I tried building the java code on my local, tried importing that as well but gets same error :| can you please help?

**Comment by DinoChiesa** [comment]
Hi Kuldeep
Usually the problem when you see that symptom is that you don't have all the dependencies deployed with the API Proxy.  Check it and try again?  This callout is in broad use, so I'm certain that it's not an issue with the code.

**Comment by bhatikuldeep** [comment]
@DinoChiesa sure, I will give it a try again and let you know, thanks!
